[package]
name = "anhi_native"
version = "0.1.0"
edition = "2021"

[lib]
name = "anhi_native"
crate-type = ["cdylib"]

[dependencies]
anyhow = { version = "1.0.55", features = ["backtrace"] }
flutter_rust_bridge = "1.22"
bcrypt = "0.12"
sha256 = "1.0"